### ISSUE TITLE
UnsupportedOperationException: Minus sign spans multiple characters: ‏-

### ISSUE THREAD

**Issue by koral--** [ThreeTen/threetenbp#100]
Issue happens on Samsung Galaxy J5 with Android 5.1.1. Library version 1.3.8. On other devices it is fine.

Stacktrace:
```
     Caused by: java.lang.UnsupportedOperationException: Minus sign spans multiple characters: ‏-
        at java.text.DecimalFormatSymbols.getMinusSign(DecimalFormatSymbols.java:300)
        at org.threeten.bp.format.DecimalStyle.create(DecimalStyle.java:130)
        at org.threeten.bp.format.DecimalStyle.of(DecimalStyle.java:119)
        at org.threeten.bp.format.DecimalStyle.ofDefaultLocale(DecimalStyle.java:104)
```
Snippet which reproduces this issue:
```kotlin
Locale.setDefault(Locale.forLanguageTag("ar-SA-u-nu-arab"))
val decimalStyle = DecimalStyle.ofDefaultLocale()      
println(LocalDate.now().format(DateTimeFormatter.ofLocalizedDate(FormatStyle.SHORT).withDecimalStyle(decimalStyle)))
```
`DecimalFormatSymbols` at `DecimalStyle:130` looks like that on debugger:
```
oldSymbols = {DecimalFormatSymbols@19741} "java.text.DecimalFormatSymbols[currency=SAR,currencySymbol=ر.س.‏,decimalSeparator=٫,digit=#,exponentSeparator=اس,groupingSeparator=٬,infinity=∞,intlCurrencySymbol=SAR,minusSign=‏-,monetarySeparator=٫,NaN=ليس رقم,patternSeparator=؛,perMill=؉,percent=‏٪,zeroDigit=٠]"
 NaN = "ليس رقم"
 currency = {Currency@19750} "SAR"
 currencySymbol = "ر.س.‏"
 decimalSeparator = '٫' 1643
 digit = '#' 35
 exponentSeparator = "اس"
 groupingSeparator = '٬' 1644
 infinity = "∞"
 intlCurrencySymbol = "SAR"
 locale = {Locale@19740} "ar_SA_#u-nu-arab"
 minusSign = "‏-"
 monetarySeparator = '٫' 1643
 patternSeparator = '؛' 1563
 perMill = '؉' 1545
 percent = "‏٪"
 zeroDigit = '٠' 1632
```

**Comment by jodastephen** [comment]
Works in Java 8. Looks like [this Android issue](https://stackoverflow.com/questions/30655767/decimalformatsymbols-exception).
