### ISSUE TITLE
Unable to obtain LocalDateTime from TemporalAccessor exception while parsing

### ISSUE THREAD

**Issue by saravana-thiyagaraj** [ThreeTen/threetenbp#119]
Version: 1.4.1
Platform: Android

```
val date = "Feb 18, Tue, 11:59 PM"
val formatter = DateTimeFormatter.ofPattern("MMM dd, E, hh:mm a")
LocalDateTime.parse(date, formatter)
```
The above code throws the following exception
```
2020-02-17 22:28:43.857 26778-26778/com.freshdesk.helpdesk E/UncaughtException: org.threeten.bp.format.DateTimeParseException: Text 'Feb 18, Tue, 11:59 PM' could not be parsed: Unable to obtain LocalDateTime from TemporalAccessor: DateTimeBuilder[fields={DayOfWeek=2, MonthOfYear=2, DayOfMonth=18}, ISO, null, null, 23:59], type org.threeten.bp.format.DateTimeBuilder
        at org.threeten.bp.format.DateTimeFormatter.createError(DateTimeFormatter.java:1559)
        at org.threeten.bp.format.DateTimeFormatter.parse(DateTimeFormatter.java:1496)
        at org.threeten.bp.LocalDateTime.parse(LocalDateTime.java:444)
Caused by: org.threeten.bp.DateTimeException: Unable to obtain LocalDateTime from TemporalAccessor: DateTimeBuilder[fields={DayOfWeek=2, MonthOfYear=2, DayOfMonth=18}, ISO, null, null, 23:59], type org.threeten.bp.format.DateTimeBuilder
        at org.threeten.bp.LocalDateTime.from(LocalDateTime.java:413)
        at org.threeten.bp.LocalDateTime$1.queryFrom(LocalDateTime.java:121)
        at org.threeten.bp.LocalDateTime$1.queryFrom(LocalDateTime.java:118)
        at org.threeten.bp.format.DateTimeBuilder.build(DateTimeBuilder.java:642)
        at org.threeten.bp.format.DateTimeFormatter.parse(DateTimeFormatter.java:1492)
        at org.threeten.bp.LocalDateTime.parse(LocalDateTime.java:444) 
```

But the below code works perfectly:
```
val format = LocalDateTime.of(2020, Month.FEBRUARY, 18, 23, 59).format(formatter)
```
**Output:** `Feb 18, Tue, 11:59 PM`

**Comment by thsaravana** [comment]
The problem is the date string `Feb 18, Tue, 11:59 PM` doesn't have all the components needed to construct a valid date. In this case, the YEAR is missing.

The below works perfectly:
```
val date = "Feb 18, Tue, 11:59 PM 2020"
val formatter = DateTimeFormatter.ofPattern("MMM dd, E, hh:mm a yyyy")
LocalDateTime.parse(date, formatter)
```

Result: `2020-02-18T23:59`

**Comment by jodastephen** [comment]
```
new DateTimeFormatterBuilder()
  .appendPattern("MMM dd, E, hh:mm a")
  .parseDefaulting(ChronoField.YEAR, 2020)
  .toFormatter();
```
