### ISSUE TITLE
Caused by org.threeten.bp.zone.ZoneRulesException: Unknown time-zone ID: Europe/Kyiv

### ISSUE THREAD

**Issue by nAkhmedov** [ThreeTen/threetenbp#175]
org.threeten.bp.zone.ZoneRulesException: Unknown time-zone ID: Europe/Kyiv
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4233)
       at android.app.ActivityThread.access$1800(ActivityThread.java:274)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:233)
       at android.app.ActivityThread.main(ActivityThread.java:8063)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

Caused by org.threeten.bp.zone.ZoneRulesException: Unknown time-zone ID: Europe/Kyiv
       at org.threeten.bp.zone.ZoneRulesProvider.getProvider(ZoneRulesProvider.java:167)
       at org.threeten.bp.zone.ZoneRulesProvider.getRules(ZoneRulesProvider.java:122)
       at org.threeten.bp.ZoneRegion.ofId(ZoneRegion.java:143)
       at org.threeten.bp.ZoneId.of(ZoneId.java:358)
       at org.threeten.bp.ZoneId.of(ZoneId.java:286)
       at org.threeten.bp.ZoneId.systemDefault(ZoneId.java:245)
       at org.threeten.bp.Clock.systemDefaultZone(Clock.java:137)
       at org.threeten.bp.LocalDateTime.now(LocalDateTime.java:152)

**Comment by sschaap** [comment]
This issue likely stems from a mismatch between the timezone database versions of your platform and threetenbp library. The system default timezone returned by `ZoneId#systemDefault()` is created using the identifier of the timezone returned by `java.util.TimeZone#getDefault()` which uses the platform timezone database. This ostensibly returns `Europe/Kyiv`, which TTBP then attempts to resolve to the relevant zone rules against its own zone rules provider. By default, this uses a [TTDB.dat](https://github.com/ThreeTen/threetenbp/tree/main/src/main/resources/org/threeten/bp) file included in your TTBP dependency.

The `Europe/Kyiv` timezone was introduced in the tzdb 2022b released last August. Most likely, your platform tzdb was updated to include this change, but your TTBP dependency includes an older timezone database containing only the older `Europe/Kiev` identifier. There are several ways to resolve your issue:

1. Upgrade your TTBP dependency to a release that has a newer timezone database.
2. Use a TTBP dependency without a timezone database and include your own.
3. (Android API 26+) Use the java.time APIs instead of the TTBP backport.

**Comment by Vadim-Smirnov** [comment]
Same problem. There are many crash reports from Ukrainian users. Any estimates for a fix?

**Comment by jodastephen** [comment]
Just to be clear, I don't think there is any specific fix needed here.

ThreeTen-Backport has already been released with an updated timezone data file that contains both `Europe/Kiev` and `Europe/Kyiv`. It is necessary for users of the library  to check and ensure that ThreeTen-Backport and the JDK have both been updated.

**Comment by sureshmaidaragi1** [comment]
I don't see any dependency we use in Android, we are just using

`com.jakewharton.threetenabp:threetenabp:1.4.0` If I upgrade to the latest version `com.jakewharton.threetenabp:threetenabp:1.4.4` would it solves the problem?

**Comment by ronathan** [comment]
> @sschaap I don't see any dependency as you mentioned we use in Android,
> 
> > Upgrade your TTBP dependency to a release that has a newer timezone database.
> > Use a TTBP dependency without a timezone database and include your own
> 
> we are just using
> 
> `com.jakewharton.threetenabp:threetenabp:1.4.0` If I upgrade to the latest version `com.jakewharton.threetenabp:threetenabp:1.4.4` would it solves the problem?
> 
> cc : @JakeWharton

Looks like upgrading to 1.4.4 will fix the problem: https://github.com/JakeWharton/ThreeTenABP/commit/4afabdecdaf1b898a9357f753deecb6546f3be49

**Comment by haliltprkk** [comment]
@nAkhmedov, have you been able to use the latest version of the library? If so, and your issue is fixed, could you please mark this issue as closed?

**Comment by jodastephen** [comment]
Closing as no further action needed
