### ISSUE TITLE
Unknown time-zone ID: America/Ciudad_Juarez

### ISSUE THREAD

**Issue by Armen101** [ThreeTen/threetenbp#184]
Stack-trace: 
Fatal Exception: aj.g: Unknown time-zone ID: America/Ciudad_Juarez
       at org.threeten.bp.zone.ZoneRulesProvider.getProvider(ZoneRulesProvider.java:167)
       at org.threeten.bp.zone.ZoneRulesProvider.getRules(ZoneRulesProvider.java:122)
       at org.threeten.bp.ZoneRegion.ofId(ZoneRegion.java:143)
       at org.threeten.bp.ZoneId.of(ZoneId.java:358)
       at org.threeten.bp.ZoneId.of(ZoneId.java:286)
       at org.threeten.bp.ZoneId.systemDefault(ZoneId.java:245)

threetenbp version is **1.2.4**

**Comment by sschaap** [comment]
The timezone database version in your threetenbp dependency is older than the system timezone database.

Refer to issue #175 for more information. The `America/Ciudad_Juarez` timezone was [added](https://mm.icann.org/pipermail/tz-announce/2022-November/000076.html) in tzdb 2022g.

**Comment by Armen101** [comment]
thanks @sschaap !
