### ISSUE TITLE
RMI Serialization Issue?

### ISSUE THREAD

**Issue by davidMavs** [ThreeTen/threetenbp#23]
Working on an OLD system that we are enhancing with a lot of Time/Date/Timezone functionality.  We thought JSR-310BP would be a good choice to simplify our migration to Java8 in the next year.

In local environment running Windows, Eclipse, TCServer, Java 1.7 we aren't seeing the issue.

However when we deploy to Linux TCServer 2.6.5 we get the issue when serializing ZonedDateTime to send back to the Window Swing client, Java 1.7

We are seeing the following exception in the stacktrace (more trace below)
          java.net.SocketException: Broken Pipe 
when attempting to use default serialization of a ZonedDateTime thru RMI.

Interestingly if we make the ZonedDateTime attribute transient and create our own readObject/writeObject to handle serialization it works fine.  The writeObject() merely calls:
	out.writeObject(theZonedDateTimeAttribute);

Any tips or suggestions would be appreciated!
David
----------------------------------------
More full stacktrace:

java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.write(BufferedOutputStream.java:126)
        at java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1857)
        at java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(ObjectOutputStream.java:1766)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1185)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:346)
        at java.util.ArrayList.writeObject(ArrayList.java:710)
        at sun.reflect.GeneratedMethodAccessor115.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:975)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1480)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1416)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1528)
        at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:438)

**Comment by jodastephen** [comment]
Closing, as nothing to add here.
