### ISSUE TITLE
DateTimeParseException in parsing custom date

### ISSUE THREAD

**Issue by ClaudeHangui** [ThreeTen/threetenbp#75]
I'm trying to parse this date: 2017-sept-13 (or 2017-Sept-13) but I still have an exception..

This is my code : (the variable parsed corresponds to a date picked from datepicker ...so in this case I picked 2017-Sept-13 or 2017-sept-13...I get the same result when S is in uppercase or lowercase....)

` LocalDate fromCustomPattern = LocalDate.parse(parsed, DateTimeFormatter.ofPattern("yyyy-MMM-dd"));
        Log.d(TAG, "Parsed date = "+ fromCustomPattern.toString());`

This is the exception I get:
` org.threeten.bp.format.DateTimeParseException: Text '2017-sept-13' could not be parsed at index 5
                                                                                at org.threeten.bp.format.DateTimeFormatter.parseToBuilder(DateTimeFormatter.java:1587)
                                                                                at org.threeten.bp.format.DateTimeFormatter.parse(DateTimeFormatter.java:1491)
                                                                                at org.threeten.bp.LocalDate.parse(LocalDate.java:367)`

**Comment by jodastephen** [comment]
Whether this can be parsed depends on your locale (you don't say what that is) and on the parsing data available in your version of the JDK. Since the backport does not come with its own definitions of the month names, it uses those available in the JDK, which can differ from one JDK version to the next.
